name: 'SignKey'
description: 'Creates a sign key file from secret'
author: 'Ralf Beckers'

inputs:
  file: 
    description:  'name of the key file'
    required: true
    default: 'SignKey.snk'
  key:
    description:  'base64 decoded key'
    
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/createkey.ps1 -file ${{ inputs.file }} -key ${{ inputs.key }} 
      shell: pwsh
  