name: 'SignKey'

description: 'Creates a sign key file from secret'

inputs:
  file: 
    description:  'name of the key file'
    required: true
    default: 'SignKey.snk'

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/createkey.ps1 -file ${{ inputs.file }} 
      shell: pwsh

      #-environment ${{ inputs.environment }} -secret ${{ inputs.secret }} -file ${{ inputs.file }} 
 